name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  build-and-test:
    name: Build & test (Linux, Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13", "3.14"]
    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libeigen3-dev libboost-dev
      - name: Set up Python ${{ matrix.python-version }} with uv
        uses: drivendataorg/setup-python-uv-action@v1.0.0
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'packages'
      - name: Build and install
        run: uv sync

      - name: Cache pre-commit deps
        if: ${{ matrix.python-version == '3.12' }}
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit/
          key: pre-commit|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}

      - name: pre-commit
        if: ${{ matrix.python-version == '3.12' }}
        run: |
          pre-commit run --all-files --show-diff-on-failure --color=always

      - name: Run tests
        run: pytest tests -x -v
